{{- if .Values.configuration.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: hass-configuration
  namespace: {{ include "home-assistant.namespace" . }}
data:
  configuration.yaml: |
    {{- tpl .Values.configuration.templateConfig . | nindent 4 }}
{{- end -}}