{{- if .Values.configuration.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-script
  namespace: {{ include "home-assistant.namespace" . }}
data:
  init.sh: |
    {{- tpl .Values.configuration.initScript . | nindent 4 }}
{{- end -}}